Update `base-script` autopkg test to just check return code

diff --git a/debian/tests/base-script b/debian/tests/base-script
--- a/debian/tests/base-script
+++ b/debian/tests/base-script
@@ -1,5 +1,7 @@
 #!/bin/sh
 # autopkgtest check: Check base functionality of eyed3 binary
 
-[ "`eyeD3 --version 2>&1`" = '0.8.3' ] || (
-    echo "FAIL: Unexpected --version response" ; exit 1)
+if ! eyeD3 --version >/dev/null; then
+    echo "FAIL: eyeD3 --version failed"
+    exit 1
+fi
